id: P002922
initial_creation_type: ocr
source_metadata:
  id: bdr:W21767
  title: ཨ་མདོ་ཁ་སྐད་ཀྱི་རྒྱུན་བཀོལ་ཚིག་ཕྲད།
  author: ''
  volumes:
    425e4674210543c19b7913034d03e4d5:
      image_group_id: I1KG14891
      title: ''
      volume_number: 1
      total_pages: 102
